title:        Michael Viveros
tagline:      Coding Chameleon
baseurl:      ""

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

